import { Montserrat } from "next/font/google";
import "./globals.css";
import React from "react";
import RecoilRootWrapper from "@/recoil/RecoilRootWrapper";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<RecoilRootWrapper>{children}</RecoilRootWrapper>
			</body>
		</html>
	);
}
