import { atom } from "recoil";

export const productsState = atom({
	key: "productsState",
	default: {
		products: [
			{
				id: 1,
				name: "27-inch Gaming Monitor",
				price: 399.99,
				category: "monitors",
				weight: 7.5,
				description:
					"High-refresh-rate gaming monitor with crisp visuals.",
				image: "27-inch-gaming-monitor.jpg",
				slug: "27-inch-gaming-monitor",
			},
			{
				id: 2,
				name: "UltraWide Curved Monitor",
				price: 899.99,
				category: "monitors",
				weight: 10,
				description:
					"Immersive curved monitor for a cinematic viewing experience.",
				image: "ultrawide-curved-monitor.jpg",
				slug: "ultraWide-curved-monitor",
			},
			{
				id: 3,
				name: "4K Professional Monitor",
				price: 549.99,
				category: "monitors",
				weight: 9,
				description:
					"High-resolution monitor for professional content creation.",
				image: "professional-monitor.jpg",
				slug: "4k-professional-monitor",
			},
			{
				id: 4,
				name: "Portable USB-C Monitor",
				price: 299.99,
				category: "monitors",
				weight: 2,
				description:
					"Compact and portable monitor for on-the-go productivity.",
				image: "usb-c-monitor.jpg",
				slug: "portable-usb-c-monitor",
			},
			{
				id: 5,
				name: "Dual Display Setup",
				price: 699.99,
				category: "monitors",
				weight: 15,
				description:
					"Dual monitors for enhanced multitasking and productivity.",
				image: "dual-display-setup.jpg",
				slug: "dual-display-setup",
			},
			{
				id: 6,
				name: "Gaming RGB Monitor",
				price: 449.99,
				category: "monitors",
				weight: 8,
				description:
					"RGB-lit gaming monitor for an immersive gaming experience.",
				image: "gaming-rgb-monitor.jpg",
				slug: "gaming-rgb-monitor",
			},
			{
				id: 7,
				name: "Curved 32-inch Monitor",
				price: 599.99,
				category: "monitors",
				weight: 11,
				description:
					"Large curved monitor for a wide and immersive display.",
				image: "curved-32-inch-monitor.jpg",
				slug: "curved-32-inch-monitor",
			},
			{
				id: 8,
				name: "Portable Touchscreen Monitor",
				price: 329.99,
				category: "monitors",
				weight: 3,
				description:
					"Touchscreen monitor for interactive and creative tasks.",
				image: "touchscreen-monitor.jpg",
				slug: "portable-touchscreen-monitor",
			},
			{
				id: 9,
				name: "HDR Ultra HD Monitor",
				price: 799.99,
				category: "monitors",
				weight: 12,
				description:
					"High Dynamic Range monitor for stunning color reproduction.",
				image: "hdr-ultra-hd-monitor.jpg",
				slug: "hdr-ultra-hd-monitor",
			},
			{
				id: 10,
				name: "Ultra-Slim Bezel Monitor",
				price: 499.99,
				category: "monitors",
				weight: 6,
				description:
					"Sleek and ultra-slim bezel monitor for a modern setup.",
				image: "ultra-slim-bezel-monitor.jpg",
				slug: "ultra-slim-bezel-monitor",
			},
			{
				id: 11,
				name: "Modern Desk Chair",
				price: 129.99,
				category: "furniture",
				weight: 12,
				description:
					"Comfortable and stylish chair for your workspace.",
				image: "desk-chair.jpg",
				slug: "modern-desk-chair",
			},
			{
				id: 12,
				name: "Convertible Sofa Bed",
				price: 799.99,
				category: "furniture",
				weight: 45,
				description: "Sofa that transforms into a comfortable bed.",
				image: "convertible-sofa.jpg",
				slug: "convertible-sofa-bed",
			},
			{
				id: 13,
				name: "Sturdy Bookshelf",
				price: 199.99,
				category: "furniture",
				weight: 28,
				description:
					"Durable bookshelf for organizing your favorite reads.",
				image: "bookshelf.jpg",
				slug: "sturdy-booksheld",
			},
			{
				id: 14,
				name: "Elegant Coffee Table",
				price: 149.99,
				category: "furniture",
				weight: 20,
				description: "Beautiful coffee table for your living room.",
				image: "coffee-table.jpg",
				slug: "elegant-coffee-table",
			},
			{
				id: 15,
				name: "Modern TV Stand",
				price: 179.99,
				category: "furniture",
				weight: 18,
				description:
					"Sleek TV stand with storage for your entertainment setup.",
				image: "tv-stand.jpg",
				slug: "modern-tv-stand",
			},
			{
				id: 16,
				name: "L-shaped Computer Desk",
				price: 249.99,
				category: "furniture",
				weight: 30,
				description:
					"L-shaped desk for a spacious and organized workspace.",
				image: "l-shaped-desk.jpg",
				slug: "l-shaped-desk",
			},
			{
				id: 17,
				name: "Comfortable Lounge Chair",
				price: 169.99,
				category: "furniture",
				weight: 22,
				description:
					"Lounge chair for a cozy and relaxing corner in your room.",
				image: "lounge-chair.jpg",
				slug: "comfortable-lounge-chair",
			},
			{
				id: 18,
				name: "Dining Room Set",
				price: 599.99,
				category: "furniture",
				weight: 50,
				description: "Complete dining room set for family gatherings.",
				image: "dining-room-set.jpg",
				slug: "dining-romm-set",
			},
			{
				id: 19,
				name: "Sleek Bedside Table",
				price: 79.99,
				category: "furniture",
				weight: 8,
				description:
					"Minimalist bedside table for your bedroom essentials.",
				image: "bedside-table.jpg",
				slug: "sleek-bedside-table",
			},
			{
				id: 20,
				name: "Compact Wardrobe",
				price: 349.99,
				category: "furniture",
				weight: 40,
				description: "Space-saving wardrobe for efficient storage.",
				image: "compact-wardrobe.jpg",
				slug: "compact-wardrobe",
			},
			{
				id: 21,
				name: "LED Desk Lamp",
				price: 34.99,
				category: "lightning",
				weight: 1,
				description:
					"Adjustable LED lamp for optimal lightning in your room.",
				image: "desk-lamp.jpg",
				slug: "led-desk-lamp",
			},
			{
				id: 22,
				name: "Smart LED Strip Lights",
				price: 29.99,
				category: "lightning",
				weight: 0.8,
				description:
					"Color-changing LED strips to enhance your room's ambiance.",
				image: "led-strip-lights.jpg",
				slug: "smart-led-strip-lights",
			},
			{
				id: 23,
				name: "Vintage Table Lamp",
				price: 49.99,
				category: "lightning",
				weight: 2,
				description:
					"Classic table lamp for a touch of vintage elegance.",
				image: "table-lamp.jpg",
				slug: "vintage-table-lamp",
			},
			{
				id: 24,
				name: "Floor Standing Lamp",
				price: 79.99,
				category: "lightning",
				weight: 5,
				description:
					"Tall standing lamp for ambient lightning in larger spaces.",
				image: "floor-standing-lamp.jpg",
				slug: "floor-standing-lamp",
			},
			{
				id: 25,
				name: "Pendant Ceiling Light",
				price: 89.99,
				category: "lightning",
				weight: 3,
				description:
					"Modern pendant light for stylish illumination from above.",
				image: "pendant-ceiling-light.jpg",
				slug: "pendant-ceiling-light",
			},
			{
				id: 26,
				name: "Desk Ring Light",
				price: 39.99,
				category: "lightning",
				weight: 1.5,
				description:
					"Ring light for optimal lightning during video calls and content creation.",
				image: "desk-ring-light.jpg",
				slug: "desk-ring-light",
			},
			{
				id: 27,
				name: "Crystal Chandelier",
				price: 199.99,
				category: "lightning",
				weight: 10,
				description:
					"Elegant crystal chandelier to add a touch of luxury to your space.",
				image: "crystal-chandelier.jpg",
				slug: "crystal-chandelier",
			},
			{
				id: 28,
				name: "Wireless LED Bedside Lamp",
				price: 44.99,
				category: "lightning",
				weight: 1.2,
				description: "Wireless and rechargeable lamp for your bedside.",
				image: "wireless-led-bedside-lamp.jpg",
				slug: "wireless-led-bedside-lamp",
			},
			{
				id: 29,
				name: "Smart Ceiling Fan with Light",
				price: 149.99,
				category: "lightning",
				weight: 8,
				description:
					"Ceiling fan with built-in smart lightning for dual functionality.",
				image: "smart-ceiling-fan.jpg",
				slug: "smart-ceiling-fan-with-light",
			},
			{
				id: 30,
				name: "Minimalist Wall Sconce",
				price: 24.99,
				category: "lightning",
				weight: 0.5,
				description:
					"Simple and minimalist wall sconce for a contemporary look.",
				image: "wall-sconce.jpg",
				slug: "minimalist-wall-sconce",
			},
			{
				id: 31,
				name: "Smart Home Assistant",
				price: 149.99,
				category: "gadgets",
				weight: 0.5,
				description:
					"Voice-activated smart assistant for your smart home.",
				image: "smart-home-assistant.jpg",
				slug: "smart-home-assistant",
			},
			{
				id: 32,
				name: "Wireless Charging Pad",
				price: 24.99,
				category: "gadgets",
				weight: 0.2,
				description:
					"Convenient wireless charging pad for your devices.",
				image: "charging-pad.jpg",
				slug: "wireless-charging-pad",
			},

			{
				id: 34,
				name: "Smartwatch",
				price: 179.99,
				category: "gadgets",
				weight: 0.3,
				description:
					"Smartwatch for tracking fitness and receiving notifications.",
				image: "smartwatch.jpg",
				slug: "smartwatch",
			},
			{
				id: 36,
				name: "Foldable Drone",
				price: 299.99,
				category: "gadgets",
				weight: 1.5,
				description:
					"Foldable drone with a high-definition camera for aerial photography.",
				image: "foldable-drone.jpg",
				slug: "foldable-drone",
			},
			{
				id: 37,
				name: "Smart Wi-Fi Plug",
				price: 19.99,
				category: "gadgets",
				weight: 0.1,
				description:
					"Wi-Fi plug for smart control of electronic devices.",
				image: "wifi-plug.jpg",
				slug: "smart-wifi-plug",
			},
			{
				id: 38,
				name: "Digital Drawing Tablet",
				price: 129.99,
				category: "gadgets",
				weight: 0.8,
				description: "Tablet for digital drawing and graphic design.",
				image: "drawing-tablet.jpg",
				slug: "digital-drawing-tablet",
			},
			{
				id: 39,
				name: "Portable Power Bank",
				price: 34.99,
				category: "gadgets",
				weight: 0.3,
				description:
					"Portable power bank for charging devices on the go.",
				image: "power-bank.jpg",
				slug: "portable-power-bank",
			},
			{
				id: 40,
				name: "Smart Home Security Camera",
				price: 89.99,
				category: "gadgets",
				weight: 0.6,
				description:
					"Security camera with smart features for home monitoring.",
				image: "security-camera.jpg",
				slug: "smart-home-security-camera",
			},
		],
	},
});
